(ns garamond.version-test
  (:require [clojure.test :refer :all]
            [garamond.version :as ver :refer [increment]])
  (:import (com.github.zafarkhaja.semver Version)))

(defn v [s] (Version/valueOf s))

(deftest inc-test
  (testing "Basics"
    (is (= (v "1.2.4")
           (increment (v "1.2.3") :patch))
        "inc patch")
    (is (= (v "1.3.0")
           (increment (v "1.2.3") :minor))
        "inc minor")
    (is (= (v "2.0.0")
           (increment (v "1.2.3") :major))
        "inc major"))
  (testing "RC / release"
    (is (= (v "2.0.0-rc.0")
           (increment (v "1.2.3") :major-rc))
        "major, first rc")
    (is (= (v "2.0.0-rc.3")
           (increment (v "2.0.0-rc.2") :major-rc))
        "major, subsequent rc")
    (is (= (v "2.0.0")
           (increment (v "2.0.0-rc.6") :major-release))
        "major release, from rc")
    (is (= (v "3.0.0")
           (increment (v "2.0.0") :major-release))
        "major release, no rc")
    (is (= (v "2.3.0-rc.0")
           (increment (v "2.2.87") :minor-rc))
        "minor, first rc")
    (is (= (v "2.4.0-rc.7")
           (increment (v "2.4.0-rc.6") :minor-rc))
        "minor, subsequent rc")
    (is (= (v "10.5.0")
           (increment (v "10.5.0-rc.6") :minor-release))
        "minor release, from rc")
    (is (= (v "2.10.0")
           (increment (v "2.9.0") :minor-release))
        "major release, no rc")))
